### ISSUE TITLE
Gears Input edit caused

### ISSUE THREAD

**Issue by amessing** [HVA-FRC-3824/RoHAWKticsScouting2017#10]
FATAL EXCEPTION: main
                  Process: frc3824.rohawkticsscouting2017, PID: 2540
                  java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
                      at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                      at java.util.ArrayList.get(ArrayList.java:308)
                      at frc3824.rohawkticsscouting2017.Views.Steamworks.GearsInput.onClick(GearsInput.java:138)
                      at android.view.View.performClick(View.java:5198)
                      at android.view.View$PerformClick.run(View.java:21147)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by amessing** [comment]
When clicking edit on the next to current gear an IndexOutOfBoundsException (as shown above) would be thrown. Bug has been resolved.
